[package]
name = "services-manager-tui"
version = "0.1.0"
description = "services manager tui"
authors = ["Matheus-git <mathiew0@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
zbus = "5.5.0"
zvariant = "5.4.0"
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
