[package]
name = "systemd-manager-tui"
version = "0.1.0"
description = "systemd manager tui"
authors = ["Matheus-git <mathiew0@gmail.com>"]
license = "MIT"
edition = "2024"

[profile.release]
codegen-units = 1
lto = true

[dependencies]
libc = "0.2"
zbus = "5.5.0"
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
